name: learning_frog_be
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypt: ^4.3.0
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.8.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  postgres: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
